# Generated by Django 4.2.3 on 2023-07-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_detail',
            field=models.URLField(default='default_image_url'),
        ),
    ]
