# Generated by Django 4.2.3 on 2023-07-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_detail',
        ),
    ]
